# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180223_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importrow',
            name='file',
        ),
    ]
