# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180224_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importfile',
            old_name='filename',
            new_name='docfile',
        ),
    ]
