# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180224_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importfile',
            name='upload',
        ),
        migrations.AlterField(
            model_name='importfile',
            name='docfile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
