# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_importrow_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ImportFile'),
        ),
    ]
