# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_sales_volume', models.DecimalField(decimal_places=20, max_digits=20)),
                ('acv_dist', models.DecimalField(decimal_places=20, max_digits=20)),
                ('competition', models.DecimalField(decimal_places=20, max_digits=20)),
                ('edlp', models.DecimalField(decimal_places=20, max_digits=20)),
                ('trade_any_promo', models.DecimalField(decimal_places=20, max_digits=20)),
                ('tv', models.DecimalField(decimal_places=20, max_digits=20)),
                ('print_value', models.DecimalField(decimal_places=20, max_digits=20)),
                ('online_display', models.DecimalField(decimal_places=20, max_digits=20)),
                ('preroll_video', models.DecimalField(decimal_places=20, max_digits=20)),
                ('paid_search', models.DecimalField(decimal_places=20, max_digits=20)),
                ('public_relations', models.DecimalField(decimal_places=20, max_digits=20)),
                ('fsi', models.DecimalField(decimal_places=20, max_digits=20)),
                ('digital_coupon', models.DecimalField(decimal_places=20, max_digits=20)),
                ('shopper_marketing', models.DecimalField(decimal_places=20, max_digits=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ImportFile')),
            ],
        ),
    ]
