# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrow',
            name='acv_dist',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='competition',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='digital_coupon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='edlp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='fsi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='online_display',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='paid_search',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='preroll_video',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='print_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='public_relations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='retail_sales_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='shopper_marketing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='trade_any_promo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='tv',
            field=models.FloatField(default=0),
        ),
    ]
