# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 00:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180224_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='retail_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
