# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 01:05
from __future__ import unicode_literals

import compress_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_importrow_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='docfile',
            field=compress_storage.models.ZipFileField(upload_to='uploads/'),
        ),
    ]
