# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180225_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
